### ISSUE TITLE
return is a key word

### ISSUE THREAD

**Issue by stoeffel** [fp-js/fj-maybe#1]
I think return is not a good name since it's a keyword.

You can't do this:

``` js
import { return } as identity from 'fj-maybe'; // breaks in babel
```

IMO we better move this to a module `fj-identity`.

**Comment by hemanth** [comment]
`import { 'return' } as identity from 'fj-maybe';` helps?

**Comment by stoeffel** [comment]
That doesn't work either.

**Comment by hemanth** [comment]
Well if at all the user wants to import only return, we must do something like

```
export {identity as return}; // in `fj-maybe` 
```

So, they can:

```
import {return as identityFn} from 'fj-maybe';
```

**Comment by stoeffel** [comment]
hmm. I still think it should be a separate module `fj-identity`. Or rename
`return` to `returns` and don't `export default` but `export returns` and
`exports bind`.

**Comment by hemanth** [comment]
mayBe should have both `return` and `bind` as per the textbook definition, but yeah `fj-identity` makes sense, will cook it tomo and I do vote for individual exports.

**Comment by stoeffel** [comment]
Cool!

hemanth.hm notifications@github.com schrieb am Mi., 25. Feb. 2015 16:37:
